[
    {
        "id": 1,
        "star_rating": 3,
        "station_name": "Jp's Food Court, Mulshi-Paud Road",
        "phone_no": 0,
        "location": "Mulshi-Paud Road, Near, Senapathy Bapat School, Valane, Maharashtra 412108",
        "city": "Pune",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 2,
        "star_rating": 2,
        "station_name": "Hotel Casa Fedora, Lonavala",
        "phone_no": 0,
        "location": "Gate No 262/1 Beside Ashoka stambh, Kusgaon Lonavala Maharashtra",
        "city": "Pune",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 3,
        "star_rating": 2,
        "station_name": "Ginger Mumbai (Andheri East)",
        "phone_no": 0,
        "location": "Teli - Gali Road, Andheri (East), Mumbai - 400069",
        "city": "Mumbai",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 4,
        "star_rating": 4,
        "station_name": "Zeon Charging Station Salem",
        "phone_no": 0,
        "location": "Near Sankagiri Toll, Tamil Nadu 637103 Phone No - +914446314004",
        "city": "Salem",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 5,
        "star_rating": 4,
        "station_name": "TML Dion Automotives, Samantarapur",
        "phone_no": 0,
        "location": "Plot No 2175, 3766, Samantarapur, Old Town, Bhubaneswar, Odisha",
        "city": "Bhubaneshwar",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 6,
        "star_rating": 5,
        "station_name": "First Mobital",
        "phone_no": 0,
        "location": "G1-211, Sitapura Industrial Area, behind genpect Tonk Road, Jaipur - 302022",
        "city": "Jaipur",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 7,
        "star_rating": 4,
        "station_name": "The Blue Roof Cafe",
        "phone_no": 0,
        "location": "236, Bhawarkua Main Rd, near Anand Super 100, Indrapuri Colony, Bhanwar Kuwa, Indore, Madhya Pradesh",
        "city": "Indore",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 8,
        "star_rating": 4,
        "station_name": "Ather Space Ahmedabad",
        "phone_no": 0,
        "location": "Shop No. 01, Ground floor, 3rd Eye Vision Opp. Shivalik Plaza, near AMA, Panjrapole CharRasta",
        "city": "Ahmedabad",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 9,
        "star_rating": 4,
        "station_name": "Tata Power Versova",
        "phone_no": 0,
        "location": "KL Walawalkar Marg, Sahayog Nagar, Bhudargarh Colony, Andheri West, Mumbai, Maharashtra 400102",
        "city": "Mumbai",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 10,
        "star_rating": 4,
        "station_name": "Phoenix Market City, Kurla (W)",
        "phone_no": 0,
        "location": "LBS Rd, Kamani, Kurla West, Kurla, Mumbai, Maharashtra 400070",
        "city": "Mumbai",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 11,
        "star_rating": 3,
        "station_name": "Brookfield, Powai",
        "phone_no": 0,
        "location": "Spectra, High St, Hiranandani Gardens, Powai, Mumbai, Maharashtra 400076",
        "city": "Mumbai",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 12,
        "star_rating": 0,
        "station_name": "IOCL Intimate FIlling Soami Nagar Charging Station",
        "phone_no": 0,
        "location": "Outer Ring Rd, Block B, Soami Nagar North, Soami Nagar, New Delhi, Delhi",
        "city": "New Delhi",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 13,
        "star_rating": 0,
        "station_name": "Plug N Go DLF Gateway Tower",
        "phone_no": 0,
        "location": "DLF Gateway Tower",
        "city": "Gurugram",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 14,
        "star_rating": 0,
        "station_name": "TML Malwa Automobiles Prashant Vihar Charging Station",
        "phone_no": 0,
        "location": "A-1/16, A Block, Prashant Vihar, Sector 14, Rohini, Delhi",
        "city": "Rohini",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 15,
        "star_rating": 0,
        "station_name": "Adishakti - Veeranpalya",
        "phone_no": 0,
        "location": "#56, Opposite Lumbini Gardens, Veeranna Palya Ring Road , Veeranna Palya, Arabic College Post",
        "city": "Bangalore",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 16,
        "star_rating": 0,
        "station_name": "KHT Motors",
        "phone_no": 0,
        "location": "Plot No.7A, Survey No.35, Devasandra Village, Devasandra Industrial Area, K.R. Puram Hobli",
        "city": "Bangalore",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 17,
        "star_rating": 0,
        "station_name": "MG Jubilant Autoworks Kuloor Padukodi Charging Station",
        "phone_no": 0,
        "location": "Survey No 38, 2, Kuloor - Kavoor Rd, Kuloor, Padukodi, Mangalore, Karnataka",
        "city": "Bangalore",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 18,
        "star_rating": 0,
        "station_name": "URS KAR motors",
        "phone_no": 0,
        "location": "Urs Kar, CH 11, New Kantharaj Urs Rd, Mysuru, Karnataka 570004",
        "city": "Mysore",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 19,
        "star_rating": 0,
        "station_name": "MG Dyuthi Automobiles Hunsur Road Charging Station",
        "phone_no": 0,
        "location": "Plot No 201, 1 & 2, Hunsur Rd, Vijayanagar 4th Stage, Hinkal, Mysuru, Karnataka",
        "city": "Mysore",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 20,
        "star_rating": 0,
        "station_name": "Lexus Motors",
        "phone_no": 0,
        "location": "Budge Budge Trunk Road, Rampur, Kolkata, West Bengal - 700141",
        "city": "Kolkata",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 21,
        "star_rating": 0,
        "station_name": "Uniworld City New Town Charging Station",
        "phone_no": 0,
        "location": "Tower 1, Uniworld City, Newtown, New Town, West Bengal 700156",
        "city": "Kolkata",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 22,
        "star_rating": 0,
        "station_name": "IOCL Nature park Makalhati charging station",
        "phone_no": 0,
        "location": "Makalhati Mauza, Kolkata, West Bengal 700088",
        "city": "Kolkata",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 23,
        "star_rating": 0,
        "station_name": "Riya Autolink, Bodakdev",
        "phone_no": 0,
        "location": "Near Rajpath Club,SG Highway,Ahmedabad,Gujarat-380054",
        "city": "Ahmedabad",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    },
    {
        "id": 24,
        "star_rating": 0,
        "station_name": "Westside, Ellisbridge",
        "phone_no": 766610176,
        "location": "Ground Floor, Abhijeet V, Netaji Rd Ellisbridge Opp. Mayor Bungalow, Ellisbridge, Ahmedabad, Gujarat",
        "city": "Ahmedabad",
        "working_hours": "9:00 am to 11:00 pm",
        "active_status": true,
        "photos": null
    }
]